



/project/6003553/af4166/network/data/selected_0_t/spatial_temporal/user_day_spatial_temporal_connect.npz








/project/6003553/af4166/network/data/selected_0_t/spatial_temporal/user_day_spatial_temporal_connect_eigen_vals.npy
/project/6003553/af4166/network/data/selected_0_t/spatial_temporal/user_day_spatial_temporal_connect_eigen_vecs.npz




Traceback (most recent call last):
  File "./code_evv.py", line 85, in <module>
  File "./code_evv.py", line 80, in main
  File "/home/af4166/py37_ski/lib/python3.7/site-packages/numpy/lib/npyio.py", line 524, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/project/6003553/af4166/network/data/selected_0_t/spatial_temporal/user_day_spatial_temporal_connect_eigen_vals.npy'
Traceback (most recent call last):
  File "./code_evv.py", line 78, in <module>
    main()
  File "./code_evv.py", line 46, in main
    SM = sparse.load_npz(P1)
  File "/home/af4166/py37_ski/lib/python3.7/site-packages/scipy/sparse/_matrix_io.py", line 131, in load_npz
    with np.load(file, **PICKLE_KWARGS) as loaded:
  File "/home/af4166/py37_ski/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/project/6003553/af4166/network/data/selected_2_t/spatial_temporal/user_day_spatial_temporal_connect.npz'
Traceback (most recent call last):
  File "./code_evv.py", line 78, in <module>
    main()
  File "./code_evv.py", line 46, in main
    SM = sparse.load_npz(P1)
  File "/home/af4166/py37_ski/lib/python3.7/site-packages/scipy/sparse/_matrix_io.py", line 131, in load_npz
    with np.load(file, **PICKLE_KWARGS) as loaded:
  File "/home/af4166/py37_ski/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/project/6003553/af4166/network/data/selected_3_t/spatial_temporal/user_day_spatial_temporal_connect.npz'
Traceback (most recent call last):
  File "./code_evv.py", line 78, in <module>
    main()
  File "./code_evv.py", line 46, in main
    SM = sparse.load_npz(P1)
  File "/home/af4166/py37_ski/lib/python3.7/site-packages/scipy/sparse/_matrix_io.py", line 131, in load_npz
    with np.load(file, **PICKLE_KWARGS) as loaded:
  File "/home/af4166/py37_ski/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/project/6003553/af4166/network/data/selected_4_t/spatial_temporal/user_day_spatial_temporal_connect.npz'
Traceback (most recent call last):
  File "./code_evv.py", line 78, in <module>
    main()
  File "./code_evv.py", line 46, in main
    SM = sparse.load_npz(P1)
  File "/home/af4166/py37_ski/lib/python3.7/site-packages/scipy/sparse/_matrix_io.py", line 131, in load_npz
    with np.load(file, **PICKLE_KWARGS) as loaded:
  File "/home/af4166/py37_ski/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/project/6003553/af4166/network/data/selected_5_t/spatial_temporal/user_day_spatial_temporal_connect.npz'
